spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: R@mySql@0900
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/inventory
    user: root
    password: R@mySql@0900
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholder-replacement: true
