spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: R@mySql@0900
    driver-class-name: com.mysql.cj.jdbc.Driver

  # security configuration
  
  # security:
  #   user:
  #     name: ratana
  #     password: R@0900

  
  # Mail server configuration
  mail:
    username: chhanratta92000@gmail.com
    password: ablu ngch ukta susu
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp: 
          auth: true
          starttls: 
            enable: true
    debug: true

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/inventory
    user: root
    password: R@mySql@0900
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholder-replacement: true
